spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ps_user_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

clients.ps-empresa.url=${PS_EMPRESA_URL:http://localhost:8081}
security.internal-key=${INTERNAL_API_KEY:mypetadmin-local-dev-only}

logging.level.root=INFO
logging.level.com.mypetadmin.ps_user=DEBUG
